#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Text-TabularDisplay
Version  : 1.38
Release  : 2
URL      : https://cpan.metacpan.org/authors/id/D/DA/DARREN/Text-TabularDisplay-1.38.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/D/DA/DARREN/Text-TabularDisplay-1.38.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libt/libtext-tabulardisplay-perl/libtext-tabulardisplay-perl_1.38-1.debian.tar.xz
Summary  : Display text in formatted table output
Group    : Development/Tools
License  : GPL-2.0
Requires: perl-Text-TabularDisplay-license
Requires: perl-Text-TabularDisplay-man

%description
NAME
Text::TabularDisplay - Display text in formatted table output
SYNOPSIS
use Text::TabularDisplay;

%package license
Summary: license components for the perl-Text-TabularDisplay package.
Group: Default

%description license
license components for the perl-Text-TabularDisplay package.


%package man
Summary: man components for the perl-Text-TabularDisplay package.
Group: Default

%description man
man components for the perl-Text-TabularDisplay package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Text-TabularDisplay-1.38
mkdir -p %{_topdir}/BUILD/Text-TabularDisplay-1.38/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Text-TabularDisplay-1.38/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Text-TabularDisplay
cp COPYING %{buildroot}/usr/share/doc/perl-Text-TabularDisplay/COPYING
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Text/TabularDisplay.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Text-TabularDisplay/COPYING

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Text::TabularDisplay.3
